### PR TITLE
Cleanup objc-code, add .gitignore

### PR DESCRIPTION
**Pull request by garnett**

### CODE REVIEW

**Comment by thomasfinch** [comment]
Thanks!

**Comment by thomasfinch** [comment]
Oh shoot

**Comment by thomasfinch** [comment]
There now it's merged :)

**Comment by garnett** [comment]
that was fast! :+1: you mind if I clean code-style stuff a little bit more? It helps me a lot when I read the code:)

**Comment by thomasfinch** [comment]
It’s completely fine, I haven’t been paying attention to the code quality so far so I’m sure it could use some work.

**Pull request merged**
