### PR TITLE
Reboot persistence (fetch only)

### PR DESCRIPTION
**Pull request by ANGOmarcello**
Added changes so that on launch Gamma Thingy checks wether it should reapply the gammatable

### CODE REVIEW

**Comment by thomasfinch** [comment]
Ah thanks, I misunderstood and thought you meant setting the switch status depending on what the current color is, but I see you meant the other way around. Thanks!

**Comment by luuuke** [comment]
Are [those 3 lines](https://github.com/thomasfinch/GammaThingy/blob/master/GammaTest/GammaController.m#L201) left over from testing?

**Comment by ANGOmarcello** [comment]
No  that is necessary after reboot to reinstate the gamma if enabled is set to 1.
Because you would it expect to be actually on if it is set to on.

**Comment by ANGOmarcello** [comment]
But I oversaw something.

It should be more something like this:
```objective-c
if ([defaults boolForKey:@"enabled"] && firstExecution){
    [self enableOrangeness];
}
```

Where firstExecution should be a boolean indicating that the Application is running for the first time so that the screen is not lit every time a fetch request happens and enabled is 1.

**Comment by luuuke** [comment]
Yep, that's what I was worried about. Maybe it's also possible to put this into one of the application delegate methods?

**Comment by ANGOmarcello** [comment]
If we put the code in the didFinishLaunchingWithOptions method it only works without user interaction if you use the VOIP Backgrounding, with the fetching backgrounding it will only be applied if you start the application manually.

So if we want to use it with the fetching it should be in a place where we can call from the didFinishLaunchingWithOptions method and from the fetching method.

So it seems that handling this in the autoChangeOrangenessIfNeeded method works best for now but it could be implemented in a more beautiful way.

I'm unsure what to do now. I changed my GammaController class with the suggestion I gave above and that works.

**Pull request merged**
