### PR TITLE
Refined auto switch logic + smaller other changes

### PR DESCRIPTION
**Pull request by luuuke**
Pretty satisfied with it how it works now.
(The logging in GammaController is a bit superfluous right now, though.)

### CODE REVIEW

**Comment by luuuke** [comment]
Just noticed that the auto switch logic is still flawed, what a bitch to get just right.

**Comment by luuuke** [comment]
Is there an issue with this pull request?

**Comment by thomasfinch** [comment]
This is fine, I just haven't had much time to work on this in the last few days and didn't have time to merge this. You can reopen it if you want and I'll try to merge it soon.

**Comment by luuuke** [comment]
Ah okay, was just about to stop development on this, I was really unsure about the legal situation. I've reopened it.

**Comment by luuuke** [comment]
I've removed my 3D Touch implementation and merged the current master of this repo instead. This should make automatic merging possible again.

**Comment by thomasfinch** [comment]
Thanks! It's so much easier when I can just click the merge button :P

**Pull request merged**
