### PR TITLE
Automatic location based temperature change

### PR DESCRIPTION
**Pull request by CasperCLD**
See #9

### CODE REVIEW

**Comment by thomasfinch** [comment]
This is awesome, thank you!

**Comment by drewfer5** [comment]
Very nice man, seems to be working well.

**Comment by drewfer5** [comment]
Ok it actually doesn't work. So far no solution to automatically change color has worked. I'm forced to open the app and enable every evening.

**Comment by nicolinuxfr** [comment]
Same here, no automatic change at all…

**Pull request merged**
